plugins:
  - jekyll-octicons
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
title: Coel programming language
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    span:
      default_lang: coel
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
optional_front_matter:
  remove_originals: true
exclude:
  - "*.rb"
  - "*.scss"
  - "*.tf"
  - "*.tfstate"
  - "*.ts"
  - "*config.js"
  - "Gemfile*"
  - "package*.json"
  - "tsconfig*.json"
  - LICENSE
  - README.md
  - bin
  - dist
  - firebase.json
  - node_modules
  - rouge
  - tmp
  - tslint.json
