plugins:
  - jekyll-titles-from-headings
title: Coel programming language
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude:
  - README.md
  - node_modules
  - tmp
  - tsconfig.json
  - tslint.json
  - "package*.json"
  - "*config.js"
  - "*.css"
  - "*.scss"
  - "*.map"
  - "*.rb"
  - "*.tf"
  - "*.tfstate"
  - "*.ts"
