title: Coel programming language
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude:
  - README.md
  - node_modules
  - "package*.json"
  - "*-config.js"
  - "*.map"
  - "*.rb"
  - "*.tf"
  - "*.tfstate"
  - "*.ts"
