plugins:
  - jekyll-octicons
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
title: Cloe programming language
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: cloe
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
optional_front_matter:
  remove_originals: true
exclude:
  - "*.rb"
  - "*.scss"
  - "*.ts"
  - "*config.js"
  - "Gemfile*"
  - "package*.json"
  - "tsconfig*.json"
  - LICENSE
  - README.md
  - bin
  - firebase.json
  - go.*
  - node_modules
  - tmp
  - tslint.json
