version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    environment:
      GOPATH: /
    steps:
      - checkout

      - run:
          name: OS Setup
          command: |
            apt -y update --fix-missing
            apt -y install bundler curl git golang inkscape nodejs npm rake zlib1g-dev
            npm install --global npm

      - run:
          name: Initialization
          command: rake init

      - run:
          name: Lint
          command: rake lint

      - run:
          name: Build
          command: rake build
